version: '3'
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    command: /nsqd --broadcast-address=nsqd --statsd-address=graphite:8125 --data-path=/data --lookupd-tcp-address=nsqlookupd:4160
    volumes:
      - /data
    depends_on:
      - nsqlookupd
      - graphite
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    # add --lookupd-http-address=nsqlookupd:4161 at command if necessary
    command: /nsqadmin --proxy-graphite=true --graphite-url=http://graphite --nsqd-http-address=nsqd:4151 --statsd-counter-format="stats_counts.%s"
    depends_on:
      - nsqlookupd
      - nsqd
      - graphite
    ports:
      - "4171:4171"
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    # command: ["rabbitmq-plugins", "enable", "rabbitmq_prometheus"]
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:v1.0.0-RC9
    networks:
      - rabbitmq_go_net
    environment:
      RABBIT_URL: "http://127.0.0.1:15672/"
  prometheus:
    image: prom/prometheus:v2.39.0
    ports:
      - 9090:9090
    volumes:
      - ./config:/etc/prometheus
  mongodb:
    image: mongo:6.0.2
    ports:
      - 27017:27017
    command: mongod
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-3
    container_name: graphite
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
  # statsdaemon:
  #   image: bitly/statsdaemon:v0.7.3
  #   container_name: statsdaemon
  nsq_exporter:
    container_name: nsq_exporter
    image: lovoo/nsq_exporter
    ports:
      - 9117:9117
    labels:
      - nsqd:nsqd
    command:
      - '-nsqd.addr=http://nsqd:4151/stats'
      - '-collect=stats.topics,stats.channels'
  # Source : https://hub.docker.com/r/bitnami/kafka
  # zookeeper:
  #   image: 'bitnami/zookeeper:3.8-debian-11'
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka:
  #   image: 'bitnami/kafka:3.2-debian-11'
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper

networks:
  rabbitmq_go_net:
  # remove driver if fails
    driver: bridge